# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aaron/Documents/AntsAgain

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aaron/Documents/AntsAgain

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/Documents/AntsAgain/CMakeFiles /home/aaron/Documents/AntsAgain/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/Documents/AntsAgain/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named antsagain

# Build rule for target.
antsagain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antsagain
.PHONY : antsagain

# fast build rule for target.
antsagain/fast:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/build
.PHONY : antsagain/fast

src/entities/ant.o: src/entities/ant.cpp.o

.PHONY : src/entities/ant.o

# target to build an object file
src/entities/ant.cpp.o:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/entities/ant.cpp.o
.PHONY : src/entities/ant.cpp.o

src/entities/ant.i: src/entities/ant.cpp.i

.PHONY : src/entities/ant.i

# target to preprocess a source file
src/entities/ant.cpp.i:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/entities/ant.cpp.i
.PHONY : src/entities/ant.cpp.i

src/entities/ant.s: src/entities/ant.cpp.s

.PHONY : src/entities/ant.s

# target to generate assembly for a file
src/entities/ant.cpp.s:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/entities/ant.cpp.s
.PHONY : src/entities/ant.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/world/cell.o: src/world/cell.cpp.o

.PHONY : src/world/cell.o

# target to build an object file
src/world/cell.cpp.o:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/cell.cpp.o
.PHONY : src/world/cell.cpp.o

src/world/cell.i: src/world/cell.cpp.i

.PHONY : src/world/cell.i

# target to preprocess a source file
src/world/cell.cpp.i:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/cell.cpp.i
.PHONY : src/world/cell.cpp.i

src/world/cell.s: src/world/cell.cpp.s

.PHONY : src/world/cell.s

# target to generate assembly for a file
src/world/cell.cpp.s:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/cell.cpp.s
.PHONY : src/world/cell.cpp.s

src/world/colony.o: src/world/colony.cpp.o

.PHONY : src/world/colony.o

# target to build an object file
src/world/colony.cpp.o:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/colony.cpp.o
.PHONY : src/world/colony.cpp.o

src/world/colony.i: src/world/colony.cpp.i

.PHONY : src/world/colony.i

# target to preprocess a source file
src/world/colony.cpp.i:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/colony.cpp.i
.PHONY : src/world/colony.cpp.i

src/world/colony.s: src/world/colony.cpp.s

.PHONY : src/world/colony.s

# target to generate assembly for a file
src/world/colony.cpp.s:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/colony.cpp.s
.PHONY : src/world/colony.cpp.s

src/world/grid.o: src/world/grid.cpp.o

.PHONY : src/world/grid.o

# target to build an object file
src/world/grid.cpp.o:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/grid.cpp.o
.PHONY : src/world/grid.cpp.o

src/world/grid.i: src/world/grid.cpp.i

.PHONY : src/world/grid.i

# target to preprocess a source file
src/world/grid.cpp.i:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/grid.cpp.i
.PHONY : src/world/grid.cpp.i

src/world/grid.s: src/world/grid.cpp.s

.PHONY : src/world/grid.s

# target to generate assembly for a file
src/world/grid.cpp.s:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/grid.cpp.s
.PHONY : src/world/grid.cpp.s

src/world/windowManager.o: src/world/windowManager.cpp.o

.PHONY : src/world/windowManager.o

# target to build an object file
src/world/windowManager.cpp.o:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/windowManager.cpp.o
.PHONY : src/world/windowManager.cpp.o

src/world/windowManager.i: src/world/windowManager.cpp.i

.PHONY : src/world/windowManager.i

# target to preprocess a source file
src/world/windowManager.cpp.i:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/windowManager.cpp.i
.PHONY : src/world/windowManager.cpp.i

src/world/windowManager.s: src/world/windowManager.cpp.s

.PHONY : src/world/windowManager.s

# target to generate assembly for a file
src/world/windowManager.cpp.s:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/windowManager.cpp.s
.PHONY : src/world/windowManager.cpp.s

src/world/world.o: src/world/world.cpp.o

.PHONY : src/world/world.o

# target to build an object file
src/world/world.cpp.o:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/world.cpp.o
.PHONY : src/world/world.cpp.o

src/world/world.i: src/world/world.cpp.i

.PHONY : src/world/world.i

# target to preprocess a source file
src/world/world.cpp.i:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/world.cpp.i
.PHONY : src/world/world.cpp.i

src/world/world.s: src/world/world.cpp.s

.PHONY : src/world/world.s

# target to generate assembly for a file
src/world/world.cpp.s:
	$(MAKE) -f CMakeFiles/antsagain.dir/build.make CMakeFiles/antsagain.dir/src/world/world.cpp.s
.PHONY : src/world/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... antsagain"
	@echo "... src/entities/ant.o"
	@echo "... src/entities/ant.i"
	@echo "... src/entities/ant.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/world/cell.o"
	@echo "... src/world/cell.i"
	@echo "... src/world/cell.s"
	@echo "... src/world/colony.o"
	@echo "... src/world/colony.i"
	@echo "... src/world/colony.s"
	@echo "... src/world/grid.o"
	@echo "... src/world/grid.i"
	@echo "... src/world/grid.s"
	@echo "... src/world/windowManager.o"
	@echo "... src/world/windowManager.i"
	@echo "... src/world/windowManager.s"
	@echo "... src/world/world.o"
	@echo "... src/world/world.i"
	@echo "... src/world/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

